export enum ROLES {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  OR = 'ROLE_OR',
};
export enum CAMPAIGNSTATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}

export enum CATEGORIESSTATUS {
  ACTIVE = 1,
  INACTIVE = 0,
}

export enum EDUCATIONSTATUS {
  ACTIVE = 1,
  INACTIVE = 0,
}