export enum ROLES {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  OR = 'ROLE_OR',
}
export enum CAMPAIGNSTATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}